# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          SNOWFLAKE
paginate:       5
baseurl:        ""
url:            https://snowflake-1117.github.io

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Hyemin
  url:          https://snowflake-1117.github.io
  email:        1117hyemin@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/snowflake-1117/snowflake-1117.github.io

# Gems
gems:
  - jekyll-paginate

# Google analytics
google-analytics:
  id: "UA-105848087-1"
